### ISSUE TITLE
Helm install on arm64-only device fails

### ISSUE THREAD

**Issue by vielmetti** [alexellis/arkade#409] opened 2021-05-23 23:53 UTC
## Expected Behaviour

`arkade install openfaas` on arm64 machine should fetch
the arm64 binary for helm, then install openfaas.

## Current Behaviour

The fetch of the arm64 (aarch64) helm binary instead gets the armv7 (32-bit arm) version,
which fails on systems that are 64-bit only like the Equinix Metal c1.large.arm (ThunderX)

```
(base) emv@ny-c1-large-arm-01:~$ sudo arkade install openfaas
Using Kubeconfig: /root/.kube/config
Client: aarch64, Linux
2021/05/23 22:35:32 User dir established as: /root/.arkade/
https://get.helm.sh/helm-v3.5.2-linux-arm.tar.gz
/tmp/linux-arm linux-arm/
/tmp/helm linux-arm/helm
/tmp/LICENSE linux-arm/LICENSE
/tmp/README.md linux-arm/README.md
2021/05/23 22:35:36 extracted tarball into /tmp: 3 files, 0 dirs (1.253811854s)
Downloaded to:  /root/.arkade/bin/helm helm
Error: fork/exec /root/.arkade/bin/helm: exec format error
```
## Possible Solution

Something about the logic in

https://github.com/alexellis/arkade/blob/master/pkg/helm/helm.go

is not quite right - will investigate.

## Steps to Reproduce (for bugs)

1. Get an arm64 system that doesn't have 32-bit operations; that's pretty rare these days, but the Equinix Metal c1.large.arm (ThunderX) is one of them.
2. Install Kubernetes using kind for arm64 (that's new)
3. Install arkade for arm64 (loads just fine)
4. `arkade install openfaas` 

## Context

I finally have a version of `kind` for arm64, and I'm trying to determine if
it's even reasonable to run it on the ThunderX. Lots and lots of slow cores!
It seems like that might be a good match for OpenFaaS running lots and lots
of little functions.

## Your Environment

* What Kubernetes distribution are you using?

kind 0.11 (HEAD) for arm64

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-14T10:11:15Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/arm64"}
* Operating System and version (e.g. Linux, Windows, MacOS):
```

```
uname -a
Linux ny-c1-large-arm-01 5.4.0-40-generic #44-Ubuntu SMP Mon Jun 22 23:59:48 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

* What arkade version is this?

```
arkade version
Version: 0.7.15
Git Commit: 426546ce181648f68380e06c572ae529f5cd6eba
```

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/alexellis
- [x] Yes
- [ ] No

**Comment by vielmetti** [comment] 2021-05-24 00:09
After manually installing the correct version of helm, the openfaas install works.

**Comment by alexellis** [comment] 2021-05-24 07:54
Looks like you've found a bug. Thanks for being a sponsor btw.

This is where we need a change:

https://github.com/alexellis/arkade/blob/master/pkg/get/tools.go#L45

https://github.com/alexellis/arkade/blob/master/pkg/get/get_test.go#L284

The tests can also be moved to a table-format from individual functions.

I'm sure that one of the guys will pick this up if I don't get there first.

Thanks again for raising this. It is a regression since I've used arkade in videos on arm64 in the past.

Alex

**Comment by alexellis** [comment] 2021-05-24 08:13
From the PR:

> arkade is a client and should be run on a desktop / laptop with a valid KUBECONFIG file, which could be pointing at an ARM, ARM64 or `x86_64` cluster

Generally, in production, we would not expect users to not log into a node and run `kubectl` or `helm` directly, but to use the client/server approach.

Might also be of interest, if for some reason your laptop cannot access your node via the Kubernetes API: https://blog.alexellis.io/get-private-kubectl-access-anywhere/

The fix will be in the next release.

Alex

**Closed** 2021-05-24 08:23 UTC
